#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative "retina_lexer"
require_relative "retina_ast"

class SyntacticError < RuntimeError

    def initialize(tok)
        @token = tok
    end

    def to_s
        "Syntactic error on: #{@token}"   
    end
end

class Parser < Racc::Parser

module_eval(<<'...end retina_parser.y/module_eval...', 'retina_parser.y', 283)

def on_error(id, token, stack)
    raise SyntacticError::new(token)
end
   
def next_token
    token = @lexer.catch_lexeme
    puts "esto es una prueba"
    puts "Token del next_token: #{token}"
    #puts [token.class, token.idAndValue[1]]

    return [false,false] unless token
    return [token.class,token]

end
   
def parse(lexer)
    @yydebug = true
    @lexer = lexer
    @tokens = []
    ast = do_parse
    return ast
end
...end retina_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    63,     2,    63,    77,    16,    17,     5,     7,    62,     8,
    62,    39,    63,    92,    89,    87,    88,    86,     4,     7,
    62,     8,    45,     9,    45,    56,    10,    56,    63,    11,
    58,    59,    58,    59,    45,    78,    62,    56,    12,   112,
    63,   113,    58,    59,    16,    17,    68,    37,    62,    64,
    45,    64,    38,    56,    16,    17,    16,    17,    58,    59,
    45,    64,    45,    16,    17,    56,    57,    49,    57,    50,
    58,    59,    51,    63,    16,    17,    52,    64,    57,    45,
    63,    62,    92,    89,    87,    88,    86,    72,    62,    64,
    73,    79,    51,    63,    57,    45,    80,    50,    56,    81,
    85,    62,    45,    58,    59,    56,    57,   108,   110,   111,
    58,    59,    45,    63,    45,    45,   118,   136,    56,   140,
   143,    62,    64,    58,    59,    63,   147,   150,    45,    64,
   154,   156,   157,    62,   158,    45,   161,   163,    56,    57,
   165,    63,    64,    58,    59,    63,    57,    45,   167,    62,
    56,   nil,   nil,    62,   nil,    58,    59,   nil,   nil,    57,
   nil,   nil,    64,    45,   nil,   nil,    56,    45,    48,   nil,
    56,    58,    59,    63,    64,    58,    59,   nil,   nil,    57,
   nil,    62,    46,   nil,    63,   nil,   nil,   nil,    63,   nil,
    64,    57,    62,    31,    64,    45,    62,   nil,    56,    29,
    30,    28,   nil,    58,    59,   nil,    45,    57,   nil,    56,
    45,    57,   nil,    56,    58,    59,    63,   nil,    58,    59,
   nil,   nil,    64,   nil,    62,   nil,    63,   nil,   nil,   nil,
   nil,   nil,   nil,    64,    62,   nil,    63,    64,    45,    57,
   nil,    56,   nil,   nil,    62,   nil,    58,    59,    45,   nil,
    57,    56,   nil,   nil,    57,   nil,    58,    59,    45,   nil,
   nil,    56,   nil,   nil,    63,    64,    58,    59,    63,   nil,
   nil,   nil,    62,   nil,   nil,    64,    62,   nil,   nil,    63,
   nil,   nil,    57,   nil,   nil,    64,    45,    62,   nil,    56,
    45,    48,    57,    56,    58,    59,   nil,   nil,    58,    59,
   nil,    45,    57,   nil,    56,   145,   nil,    63,   146,    58,
    59,    63,   nil,    64,   nil,    62,    31,    64,    63,    62,
   nil,    48,    29,    30,    28,   nil,    62,   nil,    64,    45,
    57,   nil,    56,    45,    57,   148,    56,    58,    59,    63,
    45,    58,    59,    56,   nil,    57,    31,    62,    58,    59,
    63,   nil,    29,    30,    28,   nil,    64,   nil,    62,   nil,
    64,    45,    48,   nil,    56,    48,   nil,    64,   nil,    58,
    59,   nil,    45,    57,   nil,    56,   149,    57,    48,   160,
    58,    59,   nil,   nil,    57,   nil,   nil,    31,    64,   nil,
    31,   nil,   162,    29,    30,    28,    29,    30,    28,    64,
   nil,   nil,   nil,    31,   nil,    57,   nil,   nil,   nil,    29,
    30,    28,   nil,   nil,   nil,   nil,    57,    92,    89,    87,
    88,    86,    90,    91,    95,    96,    98,    97,    93,    94,
    99,   100,    92,    89,    87,    88,    86,    90,    91,    95,
    96,    98,    97,    93,    94,    99,   100,    92,    89,    87,
    88,    86,    90,    91,    95,    96,    98,    97,    93,    94,
    99,   100,   nil,   nil,   nil,   117,    92,    89,    87,    88,
    86,    90,    91,    95,    96,    98,    97,    93,   nil,   nil,
   117,    92,    89,    87,    88,    86,    90,    91,    95,    96,
    98,    97,   nil,   134,    92,    89,    87,    88,    86,    90,
    91,    95,    96,    98,    97,    93,    94,    99,   100,    22,
   nil,   nil,   nil,   nil,    16,    17,   nil,   nil,   nil,     7,
    35,     8,    48,   nil,    32,   nil,   nil,    34,    33,   nil,
   107,   nil,   nil,    22,    31,   nil,   166,   nil,    16,    17,
    29,    30,    28,     7,    35,     8,   nil,    31,    32,   nil,
   nil,    34,    33,    29,    30,    28,    22,   nil,    31,   nil,
   nil,    16,    17,   nil,    29,    30,    28,    35,   nil,   nil,
   nil,    32,   nil,   nil,    34,    33,   nil,   nil,   nil,    22,
   nil,    31,   nil,   nil,    16,    17,   nil,    29,    30,    28,
    35,   nil,   nil,   nil,    32,   nil,   nil,    34,    33,   nil,
   nil,   nil,    22,   nil,    31,   nil,   nil,    16,    17,   nil,
    29,    30,    28,    35,   nil,   nil,   nil,    32,   nil,   nil,
    34,    33,   nil,   nil,   nil,    22,   nil,    31,   nil,   nil,
    16,    17,   nil,    29,    30,    28,    35,   nil,   nil,   nil,
    32,   nil,   nil,    34,    33,   nil,   nil,   nil,    22,   nil,
    31,   nil,   nil,    16,    17,   nil,    29,    30,    28,    35,
   nil,   nil,   nil,    32,   nil,   nil,    34,    33,   nil,   nil,
   nil,    22,   nil,    31,   nil,   nil,    16,    17,   nil,    29,
    30,    28,    35,   nil,   nil,   nil,    32,   nil,   nil,    34,
    33,   nil,   nil,   nil,   nil,   nil,    31,   nil,   nil,   nil,
   nil,   nil,    29,    30,    28,    92,    89,    87,    88,    86,
    90,    91,    95,    96,    98,    97,    93,    94,    99,   100,
    92,    89,    87,    88,    86,    90,    91,    95,    96,    98,
    97,    93,    94,    99,   100,   nil,   101,   109,    92,    89,
    87,    88,    86,    90,    91,    95,    96,    98,    97,    93,
    94,    99,   100,   nil,   105,    92,    89,    87,    88,    86,
    90,    91,    95,    96,    98,    97,    93,    94,    99,   100,
   nil,   106,    92,    89,    87,    88,    86,    90,    91,    95,
    96,    98,    97,    93,    94,    99,   100,    92,    89,    87,
    88,    86,    90,    91,    95,    96,    98,    97,    93,    94,
    99,   100,    92,    89,    87,    88,    86,    90,    91,    95,
    96,    98,    97,    93,    94,    99,   100,    92,    89,    87,
    88,    86,    90,    91,   -72,   -72,   -72,   -72,    92,    89,
    87,    88,    86,    90,    91,   -72,   -72,   -72,   -72,    92,
    89,    87,    88,    86,    90,    91,   -72,   -72,   -72,   -72,
    92,    89,    87,    88,    86,    90,    91,   -72,   -72,   -72,
   -72 ]

racc_action_check = [
    29,     0,    30,    42,    13,    13,     1,     2,    29,     2,
    30,    13,    32,   123,   123,   123,   123,   123,     0,     9,
    32,     9,    29,     3,    30,    29,     4,    30,    31,     5,
    29,    29,    30,    30,    32,    42,    31,    32,     6,    74,
    34,    74,    32,    32,     7,     7,    31,    10,    34,    29,
    31,    30,    12,    31,    21,    21,    37,    37,    31,    31,
    15,    32,    34,   113,   113,    34,    29,    20,    30,    22,
    34,    34,    23,    50,   140,   140,    28,    31,    32,    33,
    51,    50,   124,   124,   124,   124,   124,    35,    51,    34,
    36,    43,    44,    62,    31,    50,    46,    48,    50,    49,
    52,    62,    51,    50,    50,    51,    34,    70,    72,    73,
    51,    51,    75,    63,    78,    62,    83,   108,    62,   112,
   118,    63,    50,    62,    62,    64,   136,   139,   141,    51,
   145,   147,   148,    64,   149,    63,   156,   160,    63,    50,
   162,    86,    62,    63,    63,    87,    51,    64,   166,    86,
    64,   nil,   nil,    87,   nil,    64,    64,   nil,   nil,    62,
   nil,   nil,    63,    86,   nil,   nil,    86,    87,    19,   nil,
    87,    86,    86,    88,    64,    87,    87,   nil,   nil,    63,
   nil,    88,    19,   nil,    89,   nil,   nil,   nil,    90,   nil,
    86,    64,    89,    19,    87,    88,    90,   nil,    88,    19,
    19,    19,   nil,    88,    88,   nil,    89,    86,   nil,    89,
    90,    87,   nil,    90,    89,    89,    91,   nil,    90,    90,
   nil,   nil,    88,   nil,    91,   nil,    92,   nil,   nil,   nil,
   nil,   nil,   nil,    89,    92,   nil,    93,    90,    91,    88,
   nil,    91,   nil,   nil,    93,   nil,    91,    91,    92,   nil,
    89,    92,   nil,   nil,    90,   nil,    92,    92,    93,   nil,
   nil,    93,   nil,   nil,    94,    91,    93,    93,    95,   nil,
   nil,   nil,    94,   nil,   nil,    92,    95,   nil,   nil,    96,
   nil,   nil,    91,   nil,   nil,    93,    94,    96,   nil,    94,
    95,   135,    92,    95,    94,    94,   nil,   nil,    95,    95,
   nil,    96,    93,   nil,    96,   135,   nil,    97,   135,    96,
    96,    98,   nil,    94,   nil,    97,   135,    95,    99,    98,
   nil,   137,   135,   135,   135,   nil,    99,   nil,    96,    97,
    94,   nil,    97,    98,    95,   137,    98,    97,    97,   100,
    99,    98,    98,    99,   nil,    96,   137,   100,    99,    99,
   117,   nil,   137,   137,   137,   nil,    97,   nil,   117,   nil,
    98,   100,   138,   nil,   100,   155,   nil,    99,   nil,   100,
   100,   nil,   117,    97,   nil,   117,   138,    98,   159,   155,
   117,   117,   nil,   nil,    99,   nil,   nil,   138,   100,   nil,
   155,   nil,   159,   138,   138,   138,   155,   155,   155,   117,
   nil,   nil,   nil,   159,   nil,   100,   nil,   nil,   nil,   159,
   159,   159,   nil,   nil,   nil,   nil,   117,    82,    82,    82,
    82,    82,    82,    82,    82,    82,    82,    82,    82,    82,
    82,    82,   142,   142,   142,   142,   142,   142,   142,   142,
   142,   142,   142,   142,   142,   142,   142,   104,   104,   104,
   104,   104,   104,   104,   104,   104,   104,   104,   104,   104,
   104,   104,   nil,   nil,   nil,    82,   127,   127,   127,   127,
   127,   127,   127,   127,   127,   127,   127,   127,   nil,   nil,
   142,   126,   126,   126,   126,   126,   126,   126,   126,   126,
   126,   126,   nil,   104,    69,    69,    69,    69,    69,    69,
    69,    69,    69,    69,    69,    69,    69,    69,    69,     8,
   nil,   nil,   nil,   nil,     8,     8,   nil,   nil,   nil,     8,
     8,     8,   164,   nil,     8,   nil,   nil,     8,     8,   nil,
    69,   nil,   nil,    39,     8,   nil,   164,   nil,    39,    39,
     8,     8,     8,    39,    39,    39,   nil,   164,    39,   nil,
   nil,    39,    39,   164,   164,   164,   107,   nil,    39,   nil,
   nil,   107,   107,   nil,    39,    39,    39,   107,   nil,   nil,
   nil,   107,   nil,   nil,   107,   107,   nil,   nil,   nil,   109,
   nil,   107,   nil,   nil,   109,   109,   nil,   107,   107,   107,
   109,   nil,   nil,   nil,   109,   nil,   nil,   109,   109,   nil,
   nil,   nil,   110,   nil,   109,   nil,   nil,   110,   110,   nil,
   109,   109,   109,   110,   nil,   nil,   nil,   110,   nil,   nil,
   110,   110,   nil,   nil,   nil,   146,   nil,   110,   nil,   nil,
   146,   146,   nil,   110,   110,   110,   146,   nil,   nil,   nil,
   146,   nil,   nil,   146,   146,   nil,   nil,   nil,   150,   nil,
   146,   nil,   nil,   150,   150,   nil,   146,   146,   146,   150,
   nil,   nil,   nil,   150,   nil,   nil,   150,   150,   nil,   nil,
   nil,   161,   nil,   150,   nil,   nil,   161,   161,   nil,   150,
   150,   150,   161,   nil,   nil,   nil,   161,   nil,   nil,   161,
   161,   nil,   nil,   nil,   nil,   nil,   161,   nil,   nil,   nil,
   nil,   nil,   161,   161,   161,    71,    71,    71,    71,    71,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    71,
    61,    61,    61,    61,    61,    61,    61,    61,    61,    61,
    61,    61,    61,    61,    61,   nil,    61,    71,    65,    65,
    65,    65,    65,    65,    65,    65,    65,    65,    65,    65,
    65,    65,    65,   nil,    65,    66,    66,    66,    66,    66,
    66,    66,    66,    66,    66,    66,    66,    66,    66,    66,
   nil,    66,    84,    84,    84,    84,    84,    84,    84,    84,
    84,    84,    84,    84,    84,    84,    84,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   128,   128,   128,
   128,   128,   128,   128,   128,   128,   128,   128,   129,   129,
   129,   129,   129,   129,   129,   129,   129,   129,   129,   130,
   130,   130,   130,   130,   130,   130,   130,   130,   130,   130,
   131,   131,   131,   131,   131,   131,   131,   131,   131,   131,
   131 ]

racc_action_pointer = [
   -30,     6,   -27,    -8,     2,    29,     0,    15,   485,   -15,
    -4,   nil,    32,   -25,   nil,    36,   nil,   nil,   nil,   144,
    29,    25,    18,    53,   nil,   nil,   nil,   nil,    52,    -2,
     0,    26,    10,    55,    38,    60,    52,    27,   nil,   509,
   nil,   nil,   -17,    71,    73,   nil,    76,   nil,    46,    79,
    71,    78,    80,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   716,    91,   111,   123,   734,   751,   nil,   nil,   490,
    63,   701,    71,    89,   -11,    88,   nil,   nil,    90,   nil,
   nil,   nil,   413,    66,   768,   nil,   139,   143,   171,   182,
   186,   214,   224,   234,   262,   266,   277,   305,   309,   316,
   337,   nil,   nil,   nil,   443,   nil,   nil,   532,    90,   555,
   578,   nil,    66,    34,   nil,   nil,   nil,   348,   100,   nil,
   nil,   nil,   nil,     9,    78,   nil,   477,   462,   813,   824,
   835,   846,   783,   798,   nil,   267,    81,   297,   338,    80,
    45,   104,   428,   nil,   nil,   110,   601,   104,   112,   114,
   624,   nil,   nil,   nil,   nil,   341,   100,   nil,   nil,   354,
   117,   647,   120,   nil,   498,   nil,   128,   nil ]

racc_action_default = [
   -72,   -72,   -72,   -72,   -72,   -72,   -72,   -72,   -72,   -72,
   -72,   168,   -72,   -72,    -7,   -72,   -23,   -24,    -4,   -72,
   -72,   -49,   -14,   -72,   -44,   -45,   -46,   -47,   -72,   -72,
   -72,   -72,   -72,   -72,   -72,   -72,   -72,   -72,    -1,   -72,
    -8,    -9,   -72,   -72,   -12,   -14,   -72,   -48,   -72,   -72,
   -57,   -72,   -72,   -16,   -17,   -18,   -19,   -20,   -21,   -22,
   -25,   -72,   -72,   -72,   -72,   -72,   -72,   -54,   -55,   -72,
   -72,   -72,   -72,   -72,   -72,   -72,    -3,   -10,   -72,   -11,
    -5,    -6,   -59,   -72,   -15,   -50,   -72,   -72,   -72,   -72,
   -72,   -72,   -72,   -72,   -72,   -72,   -72,   -72,   -72,   -72,
   -72,   -51,   -33,   -34,   -72,   -52,   -56,   -72,   -72,   -72,
   -72,    -2,   -68,   -72,   -70,   -13,   -58,   -72,   -72,   -26,
   -27,   -28,   -29,   -30,   -31,   -32,   -35,   -36,   -37,   -38,
   -39,   -40,   -41,   -42,   -43,   -72,   -72,   -72,   -72,   -72,
   -72,   -72,   -59,   -53,   -61,   -72,   -72,   -72,   -72,   -72,
   -72,   -69,   -71,   -60,   -62,   -72,   -72,   -65,   -66,   -72,
   -72,   -72,   -72,   -63,   -72,   -67,   -72,   -64 ]

racc_goto_table = [
    23,    47,    75,   116,    18,     6,     1,    44,    40,     3,
    13,   135,    36,   137,   138,    41,    40,    42,    43,    83,
    67,   144,    74,   139,   nil,    70,   nil,    61,    65,    66,
    69,    23,    71,   nil,   nil,    76,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    82,    84,
   155,   nil,   nil,   nil,   159,   nil,   nil,   nil,   nil,   nil,
   102,   103,   104,   153,   nil,   164,   nil,   114,   nil,   nil,
   115,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   141,   nil,
   nil,   nil,   nil,   nil,   119,   120,   121,   122,   123,   124,
   125,   126,   127,   128,   129,   130,   131,   132,   133,    23,
   nil,    23,    23,   nil,   nil,   151,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   142,   nil,    47,   nil,    47,
    47,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   152,   nil,   nil,   nil,    47,    23,   nil,
   nil,    47,    23,   nil,   nil,   nil,    47,   nil,   nil,   nil,
   nil,   nil,   nil,    23 ]

racc_goto_check = [
    12,    17,     8,    22,     5,     2,     1,    12,     7,     3,
     4,     6,     2,     6,     6,     9,     7,    10,    11,    20,
    21,    23,    24,    25,   nil,    12,   nil,    13,    13,    13,
    13,    12,    13,   nil,   nil,     5,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    13,    13,
     6,   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,   nil,
    13,    13,    13,    22,   nil,     6,   nil,    12,   nil,   nil,
    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     8,   nil,
   nil,   nil,   nil,   nil,    13,    13,    13,    13,    13,    13,
    13,    13,    13,    13,    13,    13,    13,    13,    13,    12,
   nil,    12,    12,   nil,   nil,     8,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    13,   nil,    17,   nil,    17,
    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    12,   nil,   nil,   nil,    17,    12,   nil,
   nil,    17,    12,   nil,   nil,   nil,    17,   nil,   nil,   nil,
   nil,   nil,   nil,    12 ]

racc_goto_pointer = [
   nil,     6,     3,     9,     3,    -4,   -96,    -5,   -35,     0,
     2,     3,    -8,    -2,   nil,   nil,   nil,   -18,   nil,   nil,
   -31,   -11,   -79,  -114,   -15,   -89 ]

racc_goto_default = [
   nil,   nil,    20,   nil,    21,   nil,    19,    14,    15,   nil,
   nil,    25,    55,   nil,    60,    53,    54,    24,    26,    27,
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 70, :_reduce_1,
  5, 70, :_reduce_2,
  4, 71, :_reduce_3,
  2, 71, :_reduce_4,
  3, 74, :_reduce_5,
  3, 74, :_reduce_6,
  1, 73, :_reduce_7,
  2, 73, :_reduce_8,
  2, 76, :_reduce_9,
  2, 78, :_reduce_10,
  2, 78, :_reduce_11,
  1, 79, :_reduce_12,
  3, 79, :_reduce_13,
  1, 81, :_reduce_14,
  3, 80, :_reduce_15,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 85, :_reduce_19,
  1, 85, :_reduce_20,
  1, 84, :_reduce_21,
  1, 84, :_reduce_22,
  1, 77, :_reduce_23,
  1, 77, :_reduce_24,
  1, 82, :_reduce_25,
  3, 82, :_reduce_26,
  3, 82, :_reduce_27,
  3, 82, :_reduce_28,
  3, 82, :_reduce_29,
  3, 82, :_reduce_30,
  3, 82, :_reduce_31,
  3, 82, :_reduce_32,
  2, 82, :_reduce_33,
  2, 82, :_reduce_34,
  3, 82, :_reduce_35,
  3, 82, :_reduce_36,
  3, 82, :_reduce_37,
  3, 82, :_reduce_38,
  3, 82, :_reduce_39,
  3, 82, :_reduce_40,
  3, 82, :_reduce_41,
  3, 82, :_reduce_42,
  3, 82, :_reduce_43,
  1, 75, :_reduce_44,
  1, 75, :_reduce_45,
  1, 75, :_reduce_46,
  1, 75, :_reduce_47,
  2, 75, :_reduce_48,
  1, 75, :_reduce_49,
  3, 86, :_reduce_none,
  3, 86, :_reduce_51,
  3, 86, :_reduce_52,
  5, 86, :_reduce_53,
  2, 86, :_reduce_54,
  1, 90, :_reduce_none,
  2, 90, :_reduce_56,
  0, 89, :_reduce_57,
  2, 89, :_reduce_58,
  0, 91, :_reduce_59,
  3, 91, :_reduce_60,
  5, 87, :_reduce_61,
  2, 92, :_reduce_none,
  4, 92, :_reduce_63,
  10, 88, :_reduce_64,
  6, 88, :_reduce_65,
  6, 88, :_reduce_66,
  10, 72, :_reduce_67,
  0, 94, :_reduce_none,
  2, 94, :_reduce_69,
  2, 93, :_reduce_70,
  4, 93, :_reduce_71 ]

racc_reduce_n = 72

racc_shift_n = 168

racc_token_table = {
  false => 0,
  :error => 1,
  Not => 2,
  :UMINUS => 3,
  Multip => 4,
  DivisionEx => 5,
  RestoEx => 6,
  DivisionEnt => 7,
  RestoEnt => 8,
  Suma => 9,
  Resta => 10,
  Less => 11,
  LessOrEqual => 12,
  GreaterOrEqual => 13,
  Greater => 14,
  And => 15,
  Or => 16,
  Equivalence => 17,
  Difference => 18,
  Equal => 19,
  Semicolon => 20,
  Types => 21,
  Signs => 22,
  NumeralLit => 23,
  Identifier => 24,
  ReservedWords => 25,
  Strings => 26,
  Ints => 27,
  InstMovi => 28,
  Number => 29,
  Bool => 30,
  Program => 31,
  True => 32,
  False => 33,
  With => 34,
  Repeat => 35,
  Do => 36,
  Times => 37,
  End => 38,
  If => 39,
  Then => 40,
  Else => 41,
  While => 42,
  For => 43,
  From => 44,
  To => 45,
  By => 46,
  Begin => 47,
  Func => 48,
  Return => 49,
  CurlyBracketR => 50,
  CurlyBracketL => 51,
  Comma => 52,
  Arrow => 53,
  Comillas => 54,
  Write => 55,
  Writeln => 56,
  Read => 57,
  Comments => 58,
  Forward => 59,
  Arc => 60,
  SetPosition => 61,
  RotateR => 62,
  RotateL => 63,
  Backward => 64,
  CloseEye => 65,
  OpenEye => 66,
  Home => 67,
  Floats => 68 }

racc_nt_base = 69

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "Not",
  "UMINUS",
  "Multip",
  "DivisionEx",
  "RestoEx",
  "DivisionEnt",
  "RestoEnt",
  "\"+\"",
  "Resta",
  "Less",
  "LessOrEqual",
  "GreaterOrEqual",
  "Greater",
  "And",
  "Or",
  "Equivalence",
  "Difference",
  "Equal",
  "Semicolon",
  "Types",
  "Signs",
  "NumeralLit",
  "Identifier",
  "ReservedWords",
  "Strings",
  "Ints",
  "InstMovi",
  "Number",
  "Bool",
  "Program",
  "True",
  "False",
  "With",
  "Repeat",
  "Do",
  "Times",
  "End",
  "If",
  "Then",
  "Else",
  "While",
  "For",
  "From",
  "To",
  "By",
  "Begin",
  "Func",
  "Return",
  "CurlyBracketR",
  "CurlyBracketL",
  "Comma",
  "Arrow",
  "Comillas",
  "Write",
  "Writeln",
  "Read",
  "Comments",
  "Forward",
  "Arc",
  "SetPosition",
  "RotateR",
  "RotateL",
  "Backward",
  "CloseEye",
  "OpenEye",
  "Home",
  "Floats",
  "$start",
  "S",
  "InstBlq",
  "Declfuncion",
  "ListDecl",
  "InstBlq1",
  "ListInst",
  "Decl",
  "Type",
  "Decl1",
  "ListId",
  "Asig",
  "Var",
  "Expr",
  "Term",
  "Boolean",
  "Num",
  "inst",
  "Conditional",
  "Loop",
  "InstMovi1",
  "Rreturn",
  "InstMovi2",
  "Cond1",
  "ListArg",
  "Firm" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'retina_parser.y', 94)
  def _reduce_1(val, _values, result)
    result = S.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 95)
  def _reduce_2(val, _values, result)
    result = S.new(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 100)
  def _reduce_3(val, _values, result)
    result = InstBlq.new(val[3],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 101)
  def _reduce_4(val, _values, result)
    result = InstBlq.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 106)
  def _reduce_5(val, _values, result)
    result = InstBlq1.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 107)
  def _reduce_6(val, _values, result)
    result = InstBlq1.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 112)
  def _reduce_7(val, _values, result)
    result = ListDecl.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 113)
  def _reduce_8(val, _values, result)
    result = ListDecl.new(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 118)
  def _reduce_9(val, _values, result)
    result = Decl.new(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 123)
  def _reduce_10(val, _values, result)
    result = Decl1.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 124)
  def _reduce_11(val, _values, result)
    result = Decl1.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 129)
  def _reduce_12(val, _values, result)
    result = ListId.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 130)
  def _reduce_13(val, _values, result)
    result = ListId.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 135)
  def _reduce_14(val, _values, result)
    result = Term.new(:Identifier , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 140)
  def _reduce_15(val, _values, result)
    result = Asig.new(:Var,val[0],:Expr val[2])
    result
  end
.,.,

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

module_eval(<<'.,.,', 'retina_parser.y', 153)
  def _reduce_19(val, _values, result)
    result = Term.new(:Ints , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 154)
  def _reduce_20(val, _values, result)
    result = Term.new(:Floats , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 159)
  def _reduce_21(val, _values, result)
    result = Term.new(:True , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 160)
  def _reduce_22(val, _values, result)
    result = Term.new(:False , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 165)
  def _reduce_23(val, _values, result)
    result = :Number
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 166)
  def _reduce_24(val, _values, result)
    result = :Bool
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 171)
  def _reduce_25(val, _values, result)
    result = Term.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 172)
  def _reduce_26(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 173)
  def _reduce_27(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 174)
  def _reduce_28(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 175)
  def _reduce_29(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 176)
  def _reduce_30(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 177)
  def _reduce_31(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 178)
  def _reduce_32(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 179)
  def _reduce_33(val, _values, result)
    result = UnOp.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 180)
  def _reduce_34(val, _values, result)
    result = UnOp.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 181)
  def _reduce_35(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 182)
  def _reduce_36(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 183)
  def _reduce_37(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 184)
  def _reduce_38(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 185)
  def _reduce_39(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 186)
  def _reduce_40(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 187)
  def _reduce_41(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 188)
  def _reduce_42(val, _values, result)
    result = BinOp.new(val[2], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 189)
  def _reduce_43(val, _values, result)
    result = ParenEx.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 194)
  def _reduce_44(val, _values, result)
    result = ListInst.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 195)
  def _reduce_45(val, _values, result)
    result = ListInst.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 196)
  def _reduce_46(val, _values, result)
    result = ListInst.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 197)
  def _reduce_47(val, _values, result)
    result = ListInst.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 198)
  def _reduce_48(val, _values, result)
    result = ListInst.new(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 199)
  def _reduce_49(val, _values, result)
    result = ListInst.new(val[0])
    result
  end
.,.,

# reduce 50 omitted

module_eval(<<'.,.,', 'retina_parser.y', 205)
  def _reduce_51(val, _values, result)
     result = Inst.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 206)
  def _reduce_52(val, _values, result)
     result = Inst.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 207)
  def _reduce_53(val, _values, result)
     result = Inst.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 208)
  def _reduce_54(val, _values, result)
    result = Inst.new(val[1])
    result
  end
.,.,

# reduce 55 omitted

module_eval(<<'.,.,', 'retina_parser.y', 214)
  def _reduce_56(val, _values, result)
    result = Rreturn.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 219)
  def _reduce_57(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 220)
  def _reduce_58(val, _values, result)
     result = InstMovi1.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 225)
  def _reduce_59(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 226)
  def _reduce_60(val, _values, result)
     result = InstMovi2.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 231)
  def _reduce_61(val, _values, result)
     result = Conditional.new(val[1], val[3], val[4]) 
    result
  end
.,.,

# reduce 62 omitted

module_eval(<<'.,.,', 'retina_parser.y', 237)
  def _reduce_63(val, _values, result)
     result = Cond1.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 242)
  def _reduce_64(val, _values, result)
    result = Loop.new(val[1], val[7]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 243)
  def _reduce_65(val, _values, result)
     result = Loop.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 244)
  def _reduce_66(val, _values, result)
     result = Loop.new(val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 249)
  def _reduce_67(val, _values, result)
     result = DeclFunc.new(val[1],val[3], val[5],val[7])
    result
  end
.,.,

# reduce 68 omitted

module_eval(<<'.,.,', 'retina_parser.y', 255)
  def _reduce_69(val, _values, result)
     result = Firm.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 260)
  def _reduce_70(val, _values, result)
     result = ListArg.new(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 261)
  def _reduce_71(val, _values, result)
     result = ListArg.new(val[0], val[2], val[3])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
